import {
  ArticleHeader,
  ArticleSection,
  Callout,
  StepList,
  RelatedArticles,
} from "@/components/learn"

export default function LearnAgentsChatPage() {
  return (
    <article>
      <ArticleHeader
        title="Agent Chat"
        description="Interact with your AI agents through a conversational chat interface to get answers, run tasks, and review results."
        readTime="6 min read"
      />

      <ArticleSection title="What Is Agent Chat?">
        <p>
          Agent Chat is the primary way you interact with your hired agents. Each
          agent has its own chat view where you can send messages, ask questions,
          and request actions. The agent responds with text, reasoning steps, and
          tool results — all visible in the conversation thread.
        </p>
        <p>
          Conversations are saved automatically, so you can return to any agent
          and pick up where you left off. Each conversation maintains its full
          history for reference.
        </p>
      </ArticleSection>

      <ArticleSection title="Starting a Conversation">
        <StepList
          steps={[
            {
              title: "Click the agent in your sidebar",
              description:
                "Select any hired agent from the Agents section in the left sidebar to open its chat view.",
            },
            {
              title: "Type your message",
              description:
                "Enter your question or request in the message input at the bottom of the chat.",
            },
            {
              title: "Send the message",
              description:
                "Press Enter or click the send button to submit your message to the agent.",
            },
            {
              title: "View the response",
              description:
                "The agent will process your request and respond with relevant information, actions, or follow-up questions.",
            },
          ]}
        />
      </ArticleSection>

      <ArticleSection title="Understanding Responses">
        <p>
          Agent responses can include several types of content depending on what
          you asked:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Text content</strong> — Direct answers, explanations, summaries,
            and recommendations from the agent.
          </li>
          <li>
            <strong>Reasoning steps</strong> — A transparent view of how the agent
            arrived at its response, showing the logic behind its output.
          </li>
          <li>
            <strong>Tool invocations</strong> — When an agent uses external tools
            (such as searching data or running calculations), the tool calls and
            results are shown inline.
          </li>
        </ul>
      </ArticleSection>

      <ArticleSection title="Suggested Prompts">
        <p>
          When you open a chat with an agent, you may see suggested prompts —
          pre-written questions or requests that demonstrate what the agent can do.
          These are a quick way to explore an agent&apos;s capabilities without
          having to craft a detailed prompt from scratch.
        </p>
      </ArticleSection>

      <Callout type="tip" title="Use Suggested Prompts">
        Not sure what to ask? Click one of the suggested prompts when starting a
        new conversation. They are tailored to each agent&apos;s strengths and
        give you a good starting point.
      </Callout>

      <ArticleSection title="Conversation History">
        <p>
          All conversations with your agents are automatically saved. You can view
          past conversations by navigating to the agent&apos;s chat view, where
          previous threads are listed. This makes it easy to reference earlier
          results or continue an ongoing task.
        </p>
      </ArticleSection>

      <ArticleSection title="Model Disclosure">
        <p>
          All agents on DreamTeam are powered by AI language models. When you chat
          with an agent, the responses are generated by these models based on the
          context you provide, your business information, and the agent&apos;s
          configured instructions. Agent outputs should be reviewed for accuracy,
          especially for critical business decisions.
        </p>
      </ArticleSection>

      <RelatedArticles
        articles={[
          {
            title: "Discovering & Hiring Agents",
            href: "/learn/agents/discover",
            description: "Browse the marketplace and hire agents for your workspace.",
          },
          {
            title: "Configuring Agents",
            href: "/learn/agents/configure",
            description: "Customize style, instructions, and notifications.",
          },
        ]}
      />
    </article>
  )
}
